
```{r}
paste(5,4,3,2,1, collapse='\n', paste("Blastoff!"))

```

```{r}
blastoffFor <- function(time){
              for (k in length(time):1)
              cat(k,"")
              Sys.sleep(1)
              k <- k-1
            
            Sys.sleep(1)
            cat("Blastoff!")
}
blastoffFor(5)
```

```{r}
blastoffWhile <- function(time){
       while(time!=0){
         Sys.sleep(1)
         cat(time,"")
         time <- time -1 
       }
       Sys.sleep(1)
       cat("Blastoff!")
}
blastoffWhile(5)
```

```{r}
blastoffRepeat <-function(time) {

             repeat {
             cat(time, " ")
             Sys.sleep(1)
             time <- time - 1
             if (time < 1) 
             break }
             
             Sys.sleep(1)
             cat("Blastoff!")
}
blastoffRepeat(5)
```

```{r}
getData <- function(N) {
  readline("Press Enter when you are ready:")
  result <- rep(0, N)
  for( k in 1:N) {
    Sys.sleep(runif(1,min=1,max=5))
    before <- Sys.time()
    readline("Press Enter:")
    after <- Sys.time()
  delay <- as.numeric(after-before)
    cat(rep("\n",20))
    result[k] <- delay
 
    }
  return(result)
  }
getData(5)
```

