````{r}
reverse <- function(input) {
 return( unlist(input)[length(input):1] )
}

reverse(1:5)
```

```{r}
reverser <- function(x){

Beta <- rev(x)
return(Beta)
}
reverser(1:5)
```

```{r}
scrambler <- function(x){

Beta <- sample(x)
return(Beta)
 }
scrambler(1:5)
```

```{r}
VowelBleeper <- function(input) {
supersub <- gsub("[aeiou]","*",input)
return(supersub)
}
VowelBleeper("dog")
```

```{r}
VowelBleeperOnOneString <- function(input) {
supersub <- gsub("[aeiou]","*",input)
return(supersub)
}
VowelBleeperOnOneString("dog")
```

```{r}
VowelBleeper <- function(input){
             sapply(input, FUN=VowelBleeperOnOneString)
             }
VowelBleeper(c("mom","dad"))

```

```{r}
L33tOnOneString<- function(input) {
sub <- chartr("e","3",input)
sub2 <- chartr("o","0",sub)
sub3 <- chartr("s","5",sub2)
sub4 <- chartr("g","9",sub3)
return(sub4)
}
L33tOnOneString("go")

x <- c("go", "pose", "halloween")
sapply(x,FUN=L33tOnOneString)
```

```{r}
L33t<- function(input) {
  sapply(input, FUN=L33tOnOneString)
}

L33t(c("go","pose"))

```


