Write another form of the loop ...

Where the state is maintained by a vector of $n+1$ slots, with the first two slots initialized to 0 and 1 respectively.

```{r}
fibLoop <- function(n) {
  # initialize state
  Ffirst <- 0  
  Fsecond <- 1
  # for() both sets some of the state and controls termination
  for (k in 3:n) { 
    # update the state
    newF <- Ffirst + Fsecond
    Ffirst <- Fsecond
    Fsecond <- newF
    }
  # Finished! Return the relevant aspect of the state
  return( newF )
  }
fibLoop(5)
```

Write a recursive function to add up the numbers from $n$ to zero.

```{r}

AddNSeq <- function(n) {

if (n==0) {return(0)}
if(n==1) {return(1)}

return(AddNSeq(n-1)+n)
}
AddNSeq(5)
```

Write a recursive function to add up all the numbers in a vector.  Hint: to simplify, index the vector with `[-1]`

```{r}
addRecursively <- function(v) {
  if (0 ==length(v)) return(0)
  return(addRecursively(v[-1]) + v[1])
  }

addRecursively(c(1,3,5))
```

```{r}
simpleRiemann <- function(f, a = 0, b = 1, n = 3) {
    rectangleWidth = (b - a)/n
    midpoints <- seq(a + rectangleWidth/2, b - rectangleWidth/2, length = n)
    rectangleAreas <- sapply(midpoints, f) * rectangleWidth
    return(sum(rectangleAreas))
}

```

```{r}
integrateRiemann <- function(f, a = 0, b = 1) {
    nbins <- 5
    biggerBins <- simpleRiemann(f, a = a, b = b, n = nbins)
    for (k in 1:5) {
        nbins <- nbins * 10  # much smaller bins
        smallerBins <- simpleRiemann(f, a = a, b = b, n = nbins)
        if (abs(smallerBins - biggerBins) < 1e-05) 
            break
        biggerBins <- smallerBins
    }
    return(smallerBins)
}
integrateRiemann(function(x) {
    3 * x
}, a = 0, b = 10)
```

```{r}
integrateRecursive <- function(f, a = 0, b = 1) {
    bigBins <- simpleRiemann(f, a = a, b = b, n = 5)
    smallBins <- simpleRiemann(f, a = a, b = b, n = 10)
    if (abs(bigBins - smallBins) < 1e-05) 
        return(smallBins) else {
        mid <- (a + b)/2
        total <- integrateRecursive(f, a = a, b = mid) + integrateRecursive(f, 
            a = mid, b = b)
        return(total)
    }
}
integrateRecursive(function(x) {
    3 * x
}, a = 0, b = 10)

```


```{r}
integrateRecursive <- function(f, a = 0, b = 1) {
    bigBins <- integrateRiemann(f, a = a, b = b, n = 5)
    smallBins <- integrateRiemann(f, a = a, b = b, n = 10)
    if (abs(bigBins - smallBins) < 1e-05) 
        return(smallBins) else {
        mid <- (a + b)/2
        total <- integrateRecursive(f, a = a, b = mid) + integrateRecursive(f, 
            a = mid, b = b)
        return(total)
    }
}
integrateRecursive(function(x) {
    3 * x
}, a = 0, b = 10)

```






