```{r}
toBase <- function(Z,b) {
          sofar <- c()
          repeat{
          r <- Z%%b
          sofar <- c(r,sofar)
          Z <- (Z-r)/b

          if (Z==0) break
          }
          
          return(sofar)
          }
toBase(10,2)
toBase(100,3)
toBase(1000,16)
```          

Given a character vector of digits and a numerical base

```{r}
baseToNumeric <- function(Nvec,b) {
  howMany <- length(as.character(Nvec))
  herdsize <- b^((howMany-1):0)
  count <- 1 
  finalAnswer <- 0
  for(k in 1:howMany) {
    answer <- Nvec[k] * herdsize[count]
    finalAnswer <- finalAnswer + answer
    count <- count + 1
  } 
  
  return(howMany)
} 
baseToNumeric(1010,2)

```

```{r}
baseToNumeric <- function(Nvec,b) {
  howMany <- strsplit(Nvec, split=NULL)
  herdsize <- b^((howMany-1):0)
  count <- 1 
  finalAnswer <- 0
  for(k in 1:howMany) {
    answer <- Nvec[k] * herdsize[count]
    finalAnswer <- finalAnswer + answer
    count <- count + 1
  } 
  
  return(herdsize)
} 
baseToNumeric("1010",2)

```

### As a loop
```{r}
convertAsALoop <- function(Nvec,b) {
#Initial state
sheepCount <- 0
boxSize <- 1

for( k in length(Nvec):1){
 sheepCount <- sheepCount + boxSize*Nvec[k]
 boxSize <- boxSize*b 
 }
 
 return(sheepCount)
}
convertAsALoop(1010,2)
```

